[theme]
name = "gruvbox-dark"

[theme.overrides]
good_fg = "#111111"

# file = "/home/dweisdorf/.config/i3/theme.toml"

[icons]
name = "awesome"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "networkmanager"
ap_format = "{ssid} {strength}/100"
device_format = "{icon} {ap}"
connection_format = "{devices}"
on_click = "alacritty -e nmtui"

# [[block]]
# block = "cpu"
# interval = 1

[[block]]
block = "battery"
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
